name = "backend"
compatibility_date = "2023-12-01"

[vars]
MY_VAR = "my-variable"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYjdhZGYxMzgtZTRjNC00NWU0LWE3NzYtNTI1NzE0ZDFlNzZiIiwidGVuYW50X2lkIjoiNmM3YmYyNmEyN2JlZjNlODZiYTQ0YWE5MzFjNTJlYTQzOWJmYmRlNzViNzI4ODVhMTg5ZWQ4YTQxMDdhZmQ0MyIsImludGVybmFsX3NlY3JldCI6IjgzNThlYmJjLTViNjYtNDVjZC1iYWMxLTE3ZTYzNGI2OWMzYSJ9.doseBmyMUnynu-xoxP_QvacUjm6PZqNIqI00_J_o0cA"
JWT_SECRET = "secretpassword"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"